import type React from "react";

export const s: Record<string, React.CSSProperties> = {
  root: {
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    background: "var(--bg)",
    overflow: "hidden",
  },

  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 20px",
    height: 44,
    borderBottom: "1px solid var(--border)",
    flexShrink: 0,
  },
  headerLogo: {
    fontFamily: "var(--mono)",
    fontSize: 11,
    color: "var(--accent)",
    letterSpacing: "0.2em",
  },
  headerCenter: {
    position: "absolute",
    left: "50%",
    transform: "translateX(-50%)",
  },
  headerRight: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minWidth: 140,
    justifyContent: "flex-end",
  },
  iconBtn: {
    fontFamily: "var(--mono)",
    fontSize: 13,
    background: "transparent",
    border: "1px solid",
    padding: "4px 8px",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  stopBtn: {
    fontFamily: "var(--mono)",
    fontSize: 10,
    letterSpacing: "0.14em",
    color: "var(--danger)",
    background: "transparent",
    border: "1px solid var(--danger)",
    padding: "5px 12px",
    cursor: "pointer",
  },

  main: { display: "flex", flex: 1, overflow: "hidden", minHeight: 0 },

  monitorWrap: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    borderRight: "1px solid var(--border)",
    minWidth: 0,
  },
  monitor: {
    flex: 1,
    position: "relative",
    background: "#040604",
    overflow: "hidden",
  },
  video: {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    objectFit: "contain",
    transition: "opacity 0.4s",
  },
  monitorGrid: {
    position: "absolute",
    inset: 0,
    backgroundImage:
      "linear-gradient(rgba(0,232,122,0.03) 1px, transparent 1px), linear-gradient(90deg, rgba(0,232,122,0.03) 1px, transparent 1px)",
    backgroundSize: "40px 40px",
    pointerEvents: "none",
    zIndex: 1,
  },
  scanline: {
    position: "absolute",
    left: 0,
    right: 0,
    height: 1,
    background:
      "linear-gradient(90deg, transparent 0%, rgba(0,232,122,0.5) 40%, rgba(0,232,122,0.5) 60%, transparent 100%)",
    pointerEvents: "none",
    animation: "scanline 5s linear infinite",
    zIndex: 3,
  },
  monitorOverlay: {
    position: "absolute",
    inset: 0,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 14,
    zIndex: 2,
  },
  qrWrap: {
    padding: 8,
    background: "#0a0a0a",
    border: "1px solid var(--border-bright)",
  },
  qrLabel: {
    fontFamily: "var(--mono)",
    fontSize: 10,
    color: "var(--text-muted)",
    letterSpacing: "0.18em",
    textAlign: "center",
  },
  qrSub: {
    fontFamily: "var(--mono)",
    fontSize: 13,
    color: "var(--accent)",
    letterSpacing: "0.08em",
  },
  recBadge: {
    position: "absolute",
    top: 14,
    left: 14,
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: "rgba(0,0,0,0.65)",
    padding: "4px 10px",
    zIndex: 10,
  },
  recDot: {
    width: 7,
    height: 7,
    borderRadius: "50%",
    background: "var(--danger)",
    display: "inline-block",
  },
  recText: {
    fontFamily: "var(--mono)",
    fontSize: 9,
    color: "var(--text)",
    letterSpacing: "0.18em",
  },
  mutedBadge: {
    position: "absolute",
    bottom: 14,
    right: 14,
    fontFamily: "var(--mono)",
    fontSize: 9,
    color: "var(--danger)",
    letterSpacing: "0.14em",
    background: "rgba(0,0,0,0.6)",
    padding: "3px 8px",
    zIndex: 10,
  },

  monitorFooter: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "0 16px",
    height: 32,
    borderTop: "1px solid var(--border)",
    flexShrink: 0,
  },
  mfLabel: {
    fontFamily: "var(--mono)",
    fontSize: 9,
    color: "var(--text-muted)",
    letterSpacing: "0.15em",
  },
  mfValue: {
    fontFamily: "var(--mono)",
    fontSize: 9,
    color: "var(--text)",
    letterSpacing: "0.08em",
  },
  mfSep: {
    width: 1,
    height: 12,
    background: "var(--border-bright)",
    margin: "0 4px",
    flexShrink: 0,
  },

  panel: {
    width: 264,
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    padding: "20px 20px 16px",
    gap: 0,
    overflowY: "auto",
  },
  panelDivider: { height: 1, background: "var(--border)", margin: "18px 0" },
  section: { display: "flex", flexDirection: "column", gap: 12 },
  sectionLabel: {
    fontFamily: "var(--mono)",
    fontSize: 9,
    color: "var(--text-muted)",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
  },
  rowLabel: {
    fontFamily: "var(--mono)",
    fontSize: 10,
    color: "var(--text-muted)",
    letterSpacing: "0.12em",
  },
  toggleBtn: {
    fontFamily: "var(--mono)",
    fontSize: 10,
    letterSpacing: "0.14em",
    background: "transparent",
    border: "1px solid",
    padding: "4px 10px",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  ipBlock: {
    display: "flex",
    alignItems: "baseline",
    padding: "14px 12px",
    background: "var(--surface)",
    border: "1px solid var(--border-bright)",
  },
  ipAddress: {
    fontFamily: "var(--display)",
    fontSize: 28,
    fontWeight: 800,
    color: "var(--text)",
    letterSpacing: "-0.01em",
  },
  ipPort: {
    fontFamily: "var(--mono)",
    fontSize: 13,
    color: "var(--accent)",
    letterSpacing: "0.04em",
    marginLeft: 2,
  },
  ipHint: {
    fontFamily: "var(--mono)",
    fontSize: 10,
    color: "var(--text-muted)",
    lineHeight: 1.6,
    letterSpacing: "0.04em",
  },
  startBtn: {
    width: "100%",
    padding: "13px",
    background: "var(--accent)",
    color: "#000",
    fontFamily: "var(--mono)",
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.18em",
    border: "none",
    cursor: "pointer",
    textTransform: "uppercase",
    marginBottom: 16,
  },
  panelFooter: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontFamily: "var(--mono)",
    fontSize: 9,
    color: "var(--text-muted)",
    letterSpacing: "0.1em",
  },

  updateBanner: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "8px 20px",
    background: "rgba(0,232,122,0.08)",
    borderBottom: "1px solid rgba(0,232,122,0.25)",
    flexShrink: 0,
  },
  updateText: {
    fontFamily: "var(--mono)",
    fontSize: 11,
    color: "var(--accent)",
    letterSpacing: "0.1em",
  },
  updateBtn: {
    fontFamily: "var(--mono)",
    fontSize: 10,
    letterSpacing: "0.14em",
    background: "var(--accent)",
    color: "#000",
    border: "none",
    padding: "5px 14px",
    cursor: "pointer",
    fontWeight: 700,
  },

  errorBanner: {
    padding: "8px 10px",
    background: "rgba(255,60,60,0.08)",
    border: "1px solid rgba(255,60,60,0.25)",
  },
  errorText: {
    fontFamily: "var(--mono)",
    fontSize: 9,
    color: "var(--danger)",
    letterSpacing: "0.06em",
    lineHeight: 1.6,
  },

  settingRow: { display: "flex", flexDirection: "column", gap: 8 },
  settingLabel: {
    fontFamily: "var(--mono)",
    fontSize: 10,
    color: "var(--text-muted)",
    letterSpacing: "0.12em",
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  settingInput: {
    width: "100%",
    padding: "9px 12px",
    fontFamily: "var(--mono)",
    fontSize: 13,
    color: "var(--text)",
    background: "var(--surface)",
    border: "1px solid var(--border-bright)",
    outline: "none",
    letterSpacing: "0.05em",
    transition: "border-color 0.2s",
  },
};
